
name: Master
run-name: "Master Workflow"

on:
  push:
    branches:
      - master
env:
  NODE_VERSION: '20'

jobs:
  test:
    name: Test
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: | 
       rm -rf node_modules
       rm yarn.lock
      if: runner.os != 'Windows'
    - run: | 
       Remove-Item node_modules -r -force -ErrorAction Ignore
       Remove-Item yarn.lock
      if: runner.os == 'Windows'
    - run: yarn cache clean
    - name: Install dependencies
      run: yarn install
    - name: Build extension
      run: yarn compile
    - run: xvfb-run -a yarn test
      if: runner.os == 'Linux'
    - run: yarn test
      if: runner.os != 'Linux'
  bump-version:
    needs: [test]
    if: success()
    runs-on: ubuntu-latest
    name: Bump Version
    outputs:
      newTag: ${{ steps.version-bump.outputs.newTag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name:  'Automated Version Bump'
        id: version-bump
        uses:  'paramsinghvc/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          patch-wording: 'patch,fix,fixes,Fix'
      - name: "Output Step"
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  changelog:
    needs: [bump-version]
    if: success()
    runs-on: ubuntu-latest
    name: Generate and Commit Changelog
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Pull last commit
      run: |
        git pull

    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.10
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add CHANGELOG.md
        git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
        git push

  create_artifact:
    name: Build extension from latest tag
    runs-on: ubuntu-latest
    needs: [bump-version,changelog]
    if: success()
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Checkout latest release tag
        env:
          LATEST_TAG: ${{ needs.bump-version.outputs.newTag }}
        run: |
          git pull
          git checkout $LATEST_TAG
          echo "Moved on tag $LATEST_TAG"

      - name: Prepare Artifact Folder
        run: mkdir -p out/artifact

      - name: Prepare Package
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: | 
          rm -rf node_modules
          rm yarn.lock
          yarn cache clean
          yarn install
          npm i -g @vscode/vsce

      - name: Build extension
        env:
          LATEST_TAG: ${{ needs.bump-version.outputs.newTag }}
        run: |
          vsce package --yarn -o csharpextension-${LATEST_TAG}.vsix
          mv csharpextension-${LATEST_TAG}.vsix out/artifact/csharpextension-${LATEST_TAG}.vsix

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: csharpextension-artifact
          path: out/artifact
  draft_release:
    name: Draft Release
    runs-on: ubuntu-latest
    needs: [bump-version,create_artifact]
    if: success()
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get the pushed tag
        env:
          LATEST_TAG: ${{ needs.bump-version.outputs.newTag }}
        id: get_tag
        run: echo ::set-output name=TAG::${LATEST_TAG}

      - name: Download Artifact
        env:
          LATEST_TAG: ${{ needs.bump-version.outputs.newTag }}
        uses: actions/download-artifact@master
        with:
          name: csharpextension-artifact
          path: out/artifact
      - run: |
          mv out/artifact/csharpextension-${LATEST_TAG}.vsix csharpextension-${LATEST_TAG}.vsix

      - name: Create Draft Release
        env:
          LATEST_TAG: ${{ needs.bump-version.outputs.newTag }}
        id: draft_release
        uses: softprops/action-gh-release@v1
        with:
          files: "csharpextension-${LATEST_TAG}.vsix"
          draft: true
