
name: Master
run-name: "Master Workflow"

on:
  push:
    branches:
      - master
env:
  NODE_VERSION: '16'

jobs:
  test:
    name: Test
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: | 
       rm -rf node_modules
       rm yarn.lock
      if: runner.os != 'Windows'
    - run: | 
       Remove-Item node_modules -r -force -ErrorAction Ignore
       Remove-Item yarn.lock
      if: runner.os == 'Windows'
    - run: yarn cache clean
    - name: Install dependencies
      run: yarn install
    - name: Build extension
      run: yarn compile
    - run: xvfb-run -a yarn test
      if: runner.os == 'Linux'
    - run: yarn test
      if: runner.os != 'Linux'
  bump-version:
    needs: [test]
    runs-on: ubuntu-latest
    name: Bump Version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name:  'Automated Version Bump'
        id: version-bump
        uses:  'paramsinghvc/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Output Step"
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  changelog:
    needs: [bump-version]
    runs-on: ubuntu-latest
    name: Generate and Commit Changelog

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Pull last commit
      run: |
        git pull

    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.10
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add CHANGELOG.md
        git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
        git push
