name: Publish Release

on: 
  release:
    types: [released]

env:
  NODE_VERSION: '20'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install vsce CLI
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: | 
          rm -rf node_modules
          rm yarn.lock
          yarn cache clean
          yarn install
          npm i -g @vscode/vsce

      - name: Publish
        run: |
          vsce publish --yarn --pat ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
