name: Publish Release

on: 
  release:
    types: [released]

env:
  NODE_VERSION: '16'

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
    - name: Prepare build
      uses: DerYeger/yarn-setup-action@master
      with:
        node-version: ${{ env.NODE_VERSION }}

  bump-minor:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            ref: master

      - name: Bump version for next release
        run: |
          VERSION=$(perl -ne 'while (m|"version"\W+([\d\.]+)|g) {print "$1"}' package.json)
          NEXT_VERSION=$(echo "$VERSION" | perl -pe 's/^(\d+)(\.)(\d+).*$/$1.$2.($3+1).$2.0/e')
          echo "Increasing version to $NEXT_VERSION"
          perl -pi -e "s|(\"version\"\W+)([\d\.]+)|\${1}${NEXT_VERSION}|" package.json
          git commit -a -m "Increased version after release publication to $NEXT_VERSION [skip ci]"
          git push
